function [fitresult, gof] = createFit1(temp60, cv60)
%CREATEFIT8(TEMP60,CV60)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : temp60
%      Y Output: cv60
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Nov-2017 14:40:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( temp60, cv60 );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [2.18570569362944 7.85398163397448 2.37857495898938 0.430268633367999 15.707963267949 -0.340274013921572 0.326963659230376 31.4159265358979 -1.27231219469212 0.0610790935271002 62.8318530717959 1.99882609783469 0.0545388216542374 47.1238898038469 1.91458053351051 0.0252485367553251 78.5398163397448 -0.457987507887622 0.0199056413180813 94.2477796076938 -1.32692459609055 0.0146166763612289 109.955742875643 2.94271112793391];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cv60 vs. temp60', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel temp60
ylabel cv60
grid on


