function [fitresult, gof] = createFit5(temp60, chi60_abs)
%CREATEFIT4(TEMP60,CHI60_ABS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : temp60
%      Y Output: chi60_abs
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Nov-2017 14:30:43


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( temp60, chi60_abs );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [34.6959965929175 7.85398163397448 2.23928698611143 13.2201048930975 31.4159265358979 -1.75366863445165 10.4548344366959 15.707963267949 2.53321497719879 3.45587358814632 47.1238898038469 -0.00527969222450014 2.52394308340332 62.8318530717959 1.71669249945397 0.630043128517746 94.2477796076938 -1.13467827661499 0.489526989021161 78.5398163397448 -2.19420339539203 0.263729741288413 109.955742875643 2.27619350205553];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'chi60_abs vs. temp60', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel temp60
ylabel chi60_abs
grid on


