function [fitresult, gof] = createFit3(temp100, cv100)
%CREATEFIT3(TEMP100,CV100)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : temp100
%      Y Output: cv100
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Nov-2017 13:58:10


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( temp100, cv100 );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [2.1880151832956 7.85398163397448 2.37840956462045 0.360985828091071 31.4159265358979 -1.1076012634443 0.441146210259225 15.707963267949 -0.446889993533874 0.0881444150275727 62.8318530717959 2.55283007546035 0.114639937520564 47.1238898038469 1.70187219193694 0.0551871181917509 78.5398163397448 -0.886914877882867 0.0275792575945139 109.955742875643 2.77933097462966 0.0231061706127313 94.2477796076938 -0.248466833004558];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cv100 vs. temp100', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel temp100
ylabel cv100
grid on


