function [fitresult, gof] = createFit4(temp100, chi100_abs)
%CREATEFIT4(TEMP100,CHI100_ABS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : temp100
%      Y Output: chi100_abs
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Nov-2017 14:31:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( temp100, chi100_abs );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [56.3722122587332 7.85398163397448 2.27057437889423 34.0391046731506 31.4159265358979 -1.4993903852703 24.4881356074954 15.707963267949 3.02390191799958 16.4818340707707 47.1238898038469 0.414080208500146 11.6802934383239 62.8318530717959 2.16829709836381 6.114209884984 78.5398163397448 -2.02946374988437 3.74274263899817 94.2477796076938 -0.343875982868139 2.31241994577428 109.955742875643 1.90439571309652];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'chi100_abs vs. temp100', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel temp100
ylabel chi100_abs
grid on


