function [fitresult, gof] = createFit(temp40, cv40)
%CREATEFIT8(TEMP40,CV40)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : temp40
%      Y Output: cv40
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Nov-2017 14:39:19


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( temp40, cv40 );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [2.18350396267821 7.85398163397448 2.37751183976564 0.444350504297754 15.707963267949 -0.173716374377583 0.267388564915499 31.4159265358979 -1.44891586925985 0.0461400387564272 47.1238898038469 2.92611255318113 0.045699546298526 62.8318530717959 1.66509916683263 0.0255901325140557 78.5398163397448 -0.0916969466539974 0.0171140884329875 94.2477796076938 -1.56429923540657 0.0144328260661603 109.955742875643 -3.08263994873015];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cv40 vs. temp40', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel temp40
ylabel cv40
grid on


